[test]
default = "default"

[[test.commands]]
name = "default"
command_type = "cargo"
command = "cargo"
sub_command = "test"
allowed_subcommands = []

[test.commands.env]

[build]
default = "default"

[[build.commands]]
name = "default"
command_type = "cargo"
command = "cargo"
sub_command = "build"
allowed_subcommands = []

[build.commands.env]

[run]
default = "default"

[[run.commands]]
name = "default"
command_type = "cargo"
command = "cargo"
sub_command = "run"
allowed_subcommands = []

[run.commands.env]

[bench]
default = "default"

[[bench.commands]]
name = "default"
command_type = "cargo"
command = "cargo"
sub_command = "bench"
allowed_subcommands = []

[bench.commands.env]
